const nome = 'David ';
const sobreNome = 'Leite';
const idade = 36;
const peso = 90;
const alturaEmM = 1.74;
let imc = peso/(alturaEmM * alturaEmM);
let anoDeNascimento = 2022 - idade;
console.log(nome, sobreNome, 'tem ', idade, 'anos, pesa ', peso,'kg',);
console.log('tem ', alturaEmM, 'de altura e seu IMC é de ',imc ,); 
console.log(nome ,sobreNome ,'nasceu em ',anoDeNascimento,'.');